[package]
name = "ads-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ads-proto = "0.1.0"
anyhow = "1.0.57"
byteorder = "1.4.3"